name: SCAP Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scap-integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.25.x]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Get Go dependencies
      run: go get -v -t -d ./...

    - name: Build inovacc_xsd2go
      run: go build -v ./cli/inovacc_xsd2go

    - name: Integrate
      run: |
        ./.github/workflows/scap.sh
